port: 1168
host: localhost
protocol: http
apiVersion: v1
apiEndpoint: /api
database:
    connectionString: ./data.db
certificates:
    privateKey: /etc/letsencrypt/live/lst97.tplinkdns.com/privkey.pem
    certificate: /etc/letsencrypt/live/lst97.tplinkdns.com/cert.pem
    ca: /etc/letsencrypt/live/lst97.tplinkdns.com/chain.pem
appIdentifier:
    name: stzita
environment: development
